# Generated by Django 6.0.2 on 2026-02-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0012_add_todos_delete_permission"),
        ("customers", "0008_webhook_event_log"),
        ("products", "0004_product_netsuite_item_name"),
        ("invoices", "0021_update_vat_text_to_english"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # RevenueAccount
        migrations.CreateModel(
            name="RevenueAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(help_text="SKR04 Kontonummer (z.B. '4400')", max_length=10)),
                ("name", models.CharField(help_text="Kontobezeichnung (z.B. 'Erlöse 19% USt')", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Erläuterung / Hinweis zur Verwendung")),
                ("tax_rate", models.DecimalField(blank=True, decimal_places=2, help_text="Erwarteter Steuersatz (zur Validierung, z.B. 19.00)", max_digits=5, null=True)),
                ("vat_classification", models.CharField(choices=[("domestic", "Inland"), ("eu", "EU (Reverse Charge)"), ("non_eu", "Drittland"), ("any", "Alle")], default="any", help_text="USt-Klassifizierung für automatische Zuordnung", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant")),
            ],
            options={
                "ordering": ["sort_order", "account_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="revenueaccount",
            constraint=models.UniqueConstraint(fields=("tenant", "account_number"), name="unique_revenue_account_per_tenant"),
        ),

        # TaxAccount
        migrations.CreateModel(
            name="TaxAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant")),
            ],
            options={
                "ordering": ["account_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="taxaccount",
            constraint=models.UniqueConstraint(fields=("tenant", "account_number"), name="unique_tax_account_per_tenant"),
        ),

        # RevenueAccountMapping
        migrations.CreateModel(
            name="RevenueAccountMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tax_rate", models.DecimalField(blank=True, decimal_places=2, help_text="Tax rate for automatic mapping (e.g. 19.00, 7.00, 0.00)", max_digits=5, null=True)),
                ("vat_classification", models.CharField(choices=[("domestic", "Inland"), ("eu", "EU (Reverse Charge)"), ("non_eu", "Drittland"), ("any", "Alle (Fallback)")], default="any", max_length=10)),
                ("product", models.ForeignKey(blank=True, help_text="Specific product (for exceptions, takes precedence)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="revenue_account_mappings", to="products.product")),
                ("revenue_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="mappings", to="accounting.revenueaccount")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant")),
            ],
        ),
        migrations.AddConstraint(
            model_name="revenueaccountmapping",
            constraint=models.UniqueConstraint(fields=("tenant", "product", "tax_rate", "vat_classification"), name="unique_revenue_mapping"),
        ),

        # DebitorAccount
        migrations.CreateModel(
            name="DebitorAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(blank=True, default="", help_text="DATEV account number (e.g. '10001'). Empty = not yet assigned.", max_length=10)),
                ("notes", models.TextField(blank=True, help_text="Notes (e.g. 'Legacy system: D-4711')")),
                ("customer", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="debitor_account", to="customers.customer")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant")),
            ],
            options={
                "ordering": ["account_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="debitoraccount",
            constraint=models.UniqueConstraint(condition=models.Q(("account_number__gt", "")), fields=("tenant", "account_number"), name="unique_debitor_number_per_tenant"),
        ),

        # DebitorAccountScheme
        migrations.CreateModel(
            name="DebitorAccountScheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prefix", models.CharField(blank=True, default="", help_text="Optional prefix (e.g. 'D' → D10001)", max_length=5)),
                ("start_number", models.PositiveIntegerField(default=10000, help_text="Start number for debtor accounts (SKR04 default: 10000)")),
                ("next_number", models.PositiveIntegerField(default=10001, help_text="Next number to be assigned")),
                ("end_number", models.PositiveIntegerField(default=69999, help_text="Maximum allowed number (SKR04 default: 69999)")),
                ("tenant", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="debitor_account_scheme", to="tenants.tenant")),
            ],
        ),

        # BookingEntry
        migrations.CreateModel(
            name="BookingEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_date", models.DateField(help_text="Booking date (= invoice date)")),
                ("debit_account", models.CharField(help_text="Debit account (Soll — debtor or revenue account)", max_length=10)),
                ("credit_account", models.CharField(help_text="Credit account (Haben — revenue or tax account)", max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("tax_key", models.CharField(blank=True, help_text="DATEV tax key / BU-Schlüssel (e.g. '9' for 19% USt)", max_length=5)),
                ("description", models.CharField(help_text="Booking text (e.g. 'RE 2026-0042 / Customer XY / Product Z')", max_length=255)),
                ("cost_center", models.CharField(blank=True, help_text="Optional cost center (KOST1)", max_length=20)),
                ("line_item_snapshot", models.JSONField(blank=True, help_text="Snapshot of the line item at booking time", null=True)),
                ("invoice_record", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="booking_entries", to="invoices.invoicerecord")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant")),
            ],
            options={
                "ordering": ["booking_date", "invoice_record", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="bookingentry",
            index=models.Index(fields=["tenant", "booking_date"], name="accounting__tenant__booking_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingentry",
            index=models.Index(fields=["tenant", "debit_account"], name="accounting__tenant__debit_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingentry",
            index=models.Index(fields=["tenant", "credit_account"], name="accounting__tenant__credit_idx"),
        ),

        # AccountingExport
        migrations.CreateModel(
            name="AccountingExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("export_format", models.CharField(choices=[("datev_csv", "DATEV Buchungsstapel (CSV)")], default="datev_csv", max_length=20)),
                ("file", models.FileField(blank=True, upload_to=apps.accounting.models.accounting_export_upload_path)),
                ("entry_count", models.PositiveIntegerField(default=0)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("exported_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
