# Generated by Django 6.0.2 on 2026-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, unique=True)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='local', max_length=20)),
                ('destination', models.CharField(default='s3', max_length=20)),
            ],
            options={
                'verbose_name': 'Storage Migration',
                'verbose_name_plural': 'Storage Migrations',
            },
        ),
    ]
