# Generated by Django 6.0.2 on 2026-02-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_storage_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorageMigration',
        ),
    ]
