# Generated by Django 6.0.1 on 2026-02-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='The type of action performed', max_length=10)),
                ('entity_type', models.CharField(help_text="The type of entity that was changed (e.g., 'contract', 'customer')", max_length=100)),
                ('entity_id', models.IntegerField(help_text='The ID of the entity that was changed')),
                ('entity_repr', models.CharField(help_text='Human-readable representation of the entity at the time of change', max_length=255)),
                ('changes', models.JSONField(default=dict, help_text='JSON object containing field changes with old/new values')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the change occurred')),
                ('parent_entity_type', models.CharField(blank=True, help_text='Parent entity type for related entities', max_length=100, null=True)),
                ('parent_entity_id', models.IntegerField(blank=True, help_text='Parent entity ID for related entities', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='The user who made the change (null for system changes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['entity_type'], name='audit_audit_entity__5b2f60_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['tenant', 'timestamp'], name='audit_audit_tenant__7e6e1d_idx'), models.Index(fields=['parent_entity_type', 'parent_entity_id'], name='audit_audit_parent__5ba5af_idx')],
            },
        ),
    ]
