# Generated by Django 6.0.1 on 2026-02-03 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0020_add_links_and_customer_attachments'),
        ('customers', '0004_add_links_and_customer_attachments'),
        ('tenants', '0002_add_user_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='The todo item description')),
                ('reminder_date', models.DateField(blank=True, help_text='Optional reminder date for this todo', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='If True, visible to all tenant users. If False, only visible to creator.')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this todo has been completed')),
                ('contract', models.ForeignKey(blank=True, help_text='The contract this todo is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='contracts.contract')),
                ('contract_item', models.ForeignKey(blank=True, help_text='The contract item this todo is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='contracts.contractitem')),
                ('created_by', models.ForeignKey(help_text='The user who created this todo', on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='The customer this todo is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['reminder_date', '-created_at'],
            },
        ),
    ]
