# Generated by Django 6.0.2 on 2026-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_add_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this todo was marked as completed', null=True),
        ),
    ]
