# Generated by Django 6.0.2 on 2026-02-11 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_banking_permissions'),
        ('todos', '0003_add_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='The comment text')),
                ('author', models.ForeignKey(help_text='The user who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='todo_comments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('todo', models.ForeignKey(help_text='The todo this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todos.todoitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
