"""REST views for invoice export."""
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from apps.core.permissions import get_current_user_from_request
from apps.customers.models import Customer
from apps.invoices.models import InvoiceRecord
from apps.invoices.services import InvoiceService, _get_company_language


def _resolve_invoice_language(tenant, customer_id, fallback="en"):
    """Resolve the invoice language for a customer.

    Uses the customer's invoice_language if set, otherwise falls back.
    """
    if customer_id:
        try:
            customer = Customer.objects.get(tenant=tenant, id=customer_id)
            if customer.invoice_language:
                return customer.invoice_language
        except Customer.DoesNotExist:
            pass
    return fallback


@method_decorator(csrf_exempt, name="dispatch")
class InvoicePreviewView(View):
    """REST endpoint for generating a sample invoice PDF with current template settings."""

    def get(self, request):
        user = get_current_user_from_request(request)
        if not user:
            return JsonResponse({"error": "Authentication required"}, status=401)

        company_lang = _get_company_language(user.tenant)
        language = request.GET.get("language", company_lang)
        if language not in ("de", "en"):
            language = company_lang

        service = InvoiceService(user.tenant)
        content = service.generate_preview_pdf(language=language)

        response = HttpResponse(content, content_type="application/pdf")
        response["Content-Disposition"] = 'inline; filename="invoice-preview.pdf"'
        response["Content-Length"] = len(content)
        return response


@method_decorator(csrf_exempt, name="dispatch")
class InvoicePreviewHtmlView(View):
    """REST endpoint returning a single invoice rendered as HTML for inline preview."""

    def get(self, request):
        user = get_current_user_from_request(request)
        if not user:
            return JsonResponse({"error": "Authentication required"}, status=401)

        if not user.has_perm_check("invoices", "export"):
            return JsonResponse({"error": "Permission denied"}, status=403)

        try:
            year = int(request.GET.get("year", ""))
            month = int(request.GET.get("month", ""))
            contract_id = int(request.GET.get("contract_id", ""))
        except (ValueError, TypeError):
            return JsonResponse(
                {"error": "year, month, and contract_id are required integers"},
                status=400,
            )

        if month < 1 or month > 12:
            return JsonResponse({"error": "month must be between 1 and 12"}, status=400)

        service = InvoiceService(user.tenant)
        invoices = service.get_invoices_for_month(year, month)

        # Find the invoice for this contract
        invoice = next(
            (inv for inv in invoices if inv.contract_id == contract_id), None
        )
        if not invoice:
            return JsonResponse(
                {"error": "No invoice found for this contract and month"}, status=404
            )

        # Resolve per-customer language
        company_lang = _get_company_language(user.tenant)
        language = _resolve_invoice_language(
            user.tenant, invoice.customer_id, fallback=company_lang
        )

        # Look up invoice number from finalized record
        invoice_number = ""
        try:
            record = InvoiceRecord.objects.get(
                tenant=user.tenant,
                contract_id=contract_id,
                billing_date__year=year,
                billing_date__month=month,
                status=InvoiceRecord.Status.FINALIZED,
            )
            invoice_number = record.invoice_number
        except InvoiceRecord.DoesNotExist:
            pass

        html = service.generate_invoice_html(
            invoice, language=language, invoice_number=invoice_number
        )

        return HttpResponse(html, content_type="text/html; charset=utf-8")


@method_decorator(csrf_exempt, name="dispatch")
class InvoiceRecordPdfView(View):
    """REST endpoint for downloading a single invoice record as PDF."""

    def get(self, request, record_id):
        user = get_current_user_from_request(request)
        if not user:
            return JsonResponse({"error": "Authentication required"}, status=401)

        if not user.has_perm_check("invoices", "read"):
            return JsonResponse({"error": "Permission denied"}, status=403)

        try:
            record = InvoiceRecord.objects.select_related(
                "customer", "contract"
            ).get(id=record_id, tenant=user.tenant)
        except InvoiceRecord.DoesNotExist:
            return JsonResponse({"error": "Invoice not found"}, status=404)

        # Serve stored PDF if available (generated by background task)
        if record.pdf_file:
            filename = f"invoice-{record.invoice_number}.pdf"
            record.pdf_file.open("rb")
            content = record.pdf_file.read()
            record.pdf_file.close()
            response = HttpResponse(content, content_type="application/pdf")
            response["Content-Disposition"] = f'inline; filename="{filename}"'
            response["Content-Length"] = len(content)
            return response

        # Fallback: render on-the-fly for pre-existing records without stored PDF
        company_lang = _get_company_language(user.tenant)
        language = request.GET.get("language", None)
        if not language or language not in ("de", "en"):
            language = _resolve_invoice_language(
                user.tenant, record.customer_id, fallback=company_lang
            )

        service = InvoiceService(user.tenant)
        content = service.generate_pdf_for_record(record, language=language)

        filename = f"invoice-{record.invoice_number}.pdf"
        response = HttpResponse(content, content_type="application/pdf")
        response["Content-Disposition"] = f'inline; filename="{filename}"'
        response["Content-Length"] = len(content)
        return response


@method_decorator(csrf_exempt, name="dispatch")
class InvoiceExportView(View):
    """REST endpoint for exporting invoices as PDF or ZUGFeRD."""

    def get(self, request):
        """
        Export invoices for a given month.

        Query parameters:
            year: Year (required)
            month: Month 1-12 (required)
            format: "pdf", "pdf-individual", "zugferd", or "zugferd-single" (required)
            language: "de" or "en" (optional, default "de")
            invoice_id: Invoice record ID (required for "zugferd-single")

        Returns:
            File download response with appropriate content-type and filename.
        """
        # Authenticate
        user = get_current_user_from_request(request)
        if not user:
            return JsonResponse({"error": "Authentication required"}, status=401)

        # Check permission
        if not user.has_perm_check("invoices", "export"):
            return JsonResponse({"error": "Permission denied"}, status=403)

        # Parse parameters
        try:
            year = int(request.GET.get("year", ""))
            month = int(request.GET.get("month", ""))
        except (ValueError, TypeError):
            return JsonResponse(
                {"error": "year and month are required and must be integers"},
                status=400,
            )

        if month < 1 or month > 12:
            return JsonResponse({"error": "month must be between 1 and 12"}, status=400)

        valid_formats = ("pdf", "pdf-individual", "zugferd", "zugferd-single")
        export_format = request.GET.get("format", "")
        if export_format not in valid_formats:
            return JsonResponse(
                {"error": f"format must be one of: {', '.join(valid_formats)}"},
                status=400,
            )

        # Use company country to determine default invoice language
        company_lang = _get_company_language(user.tenant)
        language = request.GET.get("language", company_lang)
        if language not in ("de", "en"):
            language = company_lang

        service = InvoiceService(user.tenant)

        # ZUGFeRD formats use persisted InvoiceRecords
        if export_format in ("zugferd", "zugferd-single"):
            return self._handle_zugferd_export(
                request, service, user, year, month, export_format, language
            )

        # Standard formats use on-demand calculated invoices
        invoices = service.get_invoices_for_month(year, month)

        if not invoices:
            return JsonResponse(
                {"error": "No invoices found for this month"}, status=404
            )

        # Enrich invoices with invoice numbers from finalized records
        records = InvoiceRecord.objects.filter(
            tenant=user.tenant,
            billing_date__year=year,
            billing_date__month=month,
            status=InvoiceRecord.Status.FINALIZED,
        ).values_list("contract_id", "invoice_number")
        invoice_number_map = {cid: num for cid, num in records}
        for inv in invoices:
            num = invoice_number_map.get(inv.contract_id)
            if num:
                inv.invoice_number = num

        # Build per-customer language map
        customer_ids = {inv.customer_id for inv in invoices}
        customer_languages = {}
        for cust in Customer.objects.filter(
            tenant=user.tenant, id__in=customer_ids
        ).only("id", "invoice_language"):
            if cust.invoice_language:
                customer_languages[cust.id] = cust.invoice_language

        # Generate export
        if export_format == "pdf":
            content = service.generate_pdf(
                invoices, language=language, customer_languages=customer_languages
            )
            filename = f"invoices-{year:04d}-{month:02d}.pdf"
            content_type = "application/pdf"

        else:  # pdf-individual
            content = service.generate_individual_pdfs(
                invoices, year, month, language=language,
                customer_languages=customer_languages,
            )
            filename = f"invoices-{year:04d}-{month:02d}.zip"
            content_type = "application/zip"

        response = HttpResponse(content, content_type=content_type)
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        response["Content-Length"] = len(content)

        return response

    def _handle_zugferd_export(self, request, service, user, year, month, fmt, language):
        """Handle ZUGFeRD export formats using persisted InvoiceRecords."""
        from apps.invoices.models import CompanyLegalData, InvoiceRecord

        # Validate company legal data exists
        try:
            user.tenant.legal_data
        except CompanyLegalData.DoesNotExist:
            return JsonResponse(
                {"error": "Company legal data must be configured for ZUGFeRD export."},
                status=400,
            )

        if fmt == "zugferd-single":
            # Single invoice export
            invoice_id = request.GET.get("invoice_id", "")
            if not invoice_id:
                return JsonResponse(
                    {"error": "invoice_id is required for zugferd-single format"},
                    status=400,
                )
            try:
                record = InvoiceRecord.objects.get(
                    id=int(invoice_id),
                    tenant=user.tenant,
                    status=InvoiceRecord.Status.FINALIZED,
                )
            except (InvoiceRecord.DoesNotExist, ValueError):
                return JsonResponse(
                    {"error": "Finalized invoice not found"}, status=404
                )

            # Use customer's invoice language if set
            record_language = _resolve_invoice_language(
                user.tenant, record.customer_id, fallback=language
            )
            content = service.generate_zugferd_pdf_for_record(record, record_language)
            filename = f"invoice-{record.invoice_number}.pdf"
            content_type = "application/pdf"

        else:
            # Batch ZUGFeRD export
            records = list(
                InvoiceRecord.objects.filter(
                    tenant=user.tenant,
                    billing_date__year=year,
                    billing_date__month=month,
                    status=InvoiceRecord.Status.FINALIZED,
                ).select_related("customer", "contract").order_by(
                    "customer_name", "billing_date"
                )
            )

            if not records:
                return JsonResponse(
                    {
                        "error": (
                            "No finalized invoices for this month. "
                            "Please generate invoices first."
                        )
                    },
                    status=404,
                )

            # Build per-customer language map for batch export
            customer_ids = {r.customer_id for r in records if r.customer_id}
            customer_languages = {}
            for cust in Customer.objects.filter(
                tenant=user.tenant, id__in=customer_ids
            ).only("id", "invoice_language"):
                if cust.invoice_language:
                    customer_languages[cust.id] = cust.invoice_language

            content = service.generate_individual_zugferd_pdfs(
                records, year, month, language, customer_languages=customer_languages
            )
            filename = f"invoices-zugferd-{year:04d}-{month:02d}.zip"
            content_type = "application/zip"

        response = HttpResponse(content, content_type=content_type)
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        response["Content-Length"] = len(content)
        return response
