# Generated by Django 6.0.1 on 2026-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='netsuite_customer_number',
            field=models.CharField(blank=True, help_text="Customer number from NetSuite (e.g., 'CUS174')", max_length=50, null=True),
        ),
    ]
