# Generated by Django 6.0.2 on 2026-02-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_links_and_customer_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of billing contact email addresses'),
        ),
    ]
