# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_invoice_import_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_language',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Language for invoices (de/en). Empty means use system default.',
                max_length=2,
            ),
        ),
    ]
