# Generated by Django 6.0.2 on 2026-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_invoice_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat_id',
            field=models.CharField(blank=True, default='', help_text='Customer VAT registration number (e.g., DE123456789)', max_length=50),
        ),
    ]
