# Generated by Django 6.0.2 on 2026-02-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_vat_id'),
        ('tenants', '0012_add_todos_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_type', models.CharField(help_text='HubSpot event type, e.g. company.creation', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='HubSpot object ID', max_length=100)),
                ('object_kind', models.CharField(blank=True, help_text='Object kind: company, product, or deal', max_length=50)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='processed', max_length=20)),
                ('result', models.CharField(blank=True, help_text='Processing result code, e.g. company_synced', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is failed')),
                ('received_at', models.DateTimeField(help_text='When the webhook event was received')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['tenant', '-received_at'], name='customers_w_tenant__c00093_idx')],
            },
        ),
    ]
