# Generated by Django 6.0.3 on 2026-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_clockodo_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerattachment',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Document category: order, contract, offer, other', max_length=50),
        ),
    ]
