# Generated by Django 6.0.4 on 2026-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_add_attachment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_term_days',
            field=models.PositiveIntegerField(blank=True, help_text='Payment term in days. Empty means use the tenant default.', null=True),
        ),
    ]
