# Generated by Django 6.0.1 on 2026-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_user_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='time_tracking_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
