# Generated by Django 6.0.1 on 2026-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_seed_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='role_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
