# Generated by Django 6.0.2 on 2026-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_add_todos_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
