# Generated by Django 6.0.3 on 2026-04-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('absence', 'Absence Report'), ('department_time', 'Department Time Analysis')], max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('recipients', models.JSONField(default=list)),
                ('send_day_of_month', models.PositiveIntegerField(default=5)),
                ('auto_finalize', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'report_type')},
            },
        ),
    ]
