# Generated by Django 6.0.2 on 2026-02-07 20:22

import apps.invoices.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0024_alter_contract_status'),
        ('customers', '0004_add_links_and_customer_attachments'),
        ('tenants', '0006_add_role_ids_to_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLegalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(help_text="Full legal name including legal form (e.g., 'Muster GmbH')", max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(default='Deutschland', max_length=100)),
                ('tax_number', models.CharField(blank=True, help_text='Steuernummer', max_length=50)),
                ('vat_id', models.CharField(blank=True, help_text='USt-IdNr.', max_length=50)),
                ('commercial_register_court', models.CharField(help_text="e.g., 'Amtsgericht München'", max_length=255)),
                ('commercial_register_number', models.CharField(help_text="e.g., 'HRB 12345'", max_length=50)),
                ('managing_directors', models.JSONField(default=list, help_text='List of managing director names (Geschäftsführer)')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('share_capital', models.CharField(blank=True, help_text="Stammkapital (e.g., '25.000,00 EUR')", max_length=50)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=19.0, help_text='Default tax rate in % (e.g., 19.00)', max_digits=5)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_data', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Company Legal Data',
                'verbose_name_plural': 'Company Legal Data',
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(default='{YYYY}-{NNNN}', help_text='Pattern with placeholders: {YYYY}, {YY}, {MM}, {NNN}, {NNNN}, {NNNNN}', max_length=100)),
                ('next_counter', models.PositiveIntegerField(default=1)),
                ('reset_period', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('never', 'Never')], default='yearly', max_length=10)),
                ('last_reset_year', models.PositiveIntegerField(blank=True, null=True)),
                ('last_reset_month', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_number_scheme', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Invoice Number Scheme',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.FileField(blank=True, help_text='Company logo for invoice header (PNG, JPG, SVG, max 5MB)', null=True, upload_to=apps.invoices.models.logo_upload_path)),
                ('accent_color', models.CharField(default='#2563eb', help_text='Hex color code for accents (e.g., #2563eb)', max_length=7)),
                ('header_text', models.TextField(blank=True, help_text='Custom text below company name in header')),
                ('footer_text', models.TextField(blank=True, help_text='Custom text at bottom of invoice (e.g., payment terms)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Invoice Template',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplateReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Reference invoice PDF (max 20MB)', upload_to=apps.invoices.models.reference_pdf_upload_path)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by user', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='invoices.invoicetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(help_text='Assigned sequential invoice number', max_length=100)),
                ('billing_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_items_snapshot', models.JSONField(help_text='Frozen copy of line items at generation time')),
                ('company_data_snapshot', models.JSONField(help_text='Frozen copy of company legal data at generation time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('contract_name', models.CharField(max_length=255)),
                ('invoice_text', models.TextField(blank=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_records', to='contracts.contract')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_records', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-billing_date', '-generated_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'invoice_number'), name='unique_invoice_number_per_tenant')],
            },
        ),
    ]
