# Generated by Django 6.0.2 on 2026-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_add_invoice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplatereference',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Extracted legal data, design, and layout from Claude API', null=True),
        ),
        migrations.AddField(
            model_name='invoicetemplatereference',
            name='extraction_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='', help_text='Status of data extraction from this PDF', max_length=10),
        ),
    ]
