# Generated by Django 6.0.2 on 2026-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoicetemplatereference_extracted_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylegaldata',
            name='bic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='companylegaldata',
            name='iban',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
