# Generated by Django 6.0.2 on 2026-02-11 21:02

import apps.invoices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_imported_invoice'),
        ('customers', '0004_add_links_and_customer_attachments'),
        ('invoices', '0003_alter_companylegaldata_bic_and_more'),
        ('tenants', '0008_add_banking_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice number extracted from PDF', max_length=100)),
                ('invoice_date', models.DateField(blank=True, help_text='Invoice date extracted from PDF', null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total gross amount extracted from PDF', max_digits=14, null=True)),
                ('currency', models.CharField(default='EUR', help_text='Currency code', max_length=3)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name extracted from PDF', max_length=255)),
                ('pdf_file', models.FileField(help_text='Uploaded invoice PDF', upload_to=apps.invoices.models.imported_invoice_upload_path)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('extraction_failed', 'Extraction Failed'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('extraction_error', models.TextField(blank=True, help_text='Error message if extraction failed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Matched customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_invoices', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePaymentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('invoice_number', 'Invoice Number Match'), ('amount_customer', 'Amount + Customer Match'), ('manual', 'Manual Match')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Match confidence score (0.00-1.00)', max_digits=3)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_matches', to='invoices.importedinvoice')),
                ('matched_by', models.ForeignKey(blank=True, help_text='User who created manual match (null for auto matches)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_matches', to='banking.banktransaction')),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='importedinvoice',
            index=models.Index(fields=['tenant', 'invoice_number'], name='invoices_im_tenant__f1347c_idx'),
        ),
        migrations.AddIndex(
            model_name='importedinvoice',
            index=models.Index(fields=['tenant', 'extraction_status'], name='invoices_im_tenant__fc256e_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentmatch',
            constraint=models.UniqueConstraint(fields=('invoice', 'transaction'), name='unique_invoice_transaction_match'),
        ),
    ]
