# Generated by Django 6.0.2 on 2026-02-12 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_invoice_import_batch'),
        ('invoices', '0005_enable_pg_trgm'),
        ('tenants', '0008_add_banking_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importedinvoice',
            name='expected_filename',
            field=models.CharField(blank=True, help_text='Expected filename from CSV (for matching uploaded PDFs)', max_length=255),
        ),
        migrations.AddField(
            model_name='importedinvoice',
            name='receiver_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of receiver email addresses from CSV'),
        ),
        migrations.AddField(
            model_name='importedinvoice',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded')], default='uploaded', help_text='Upload status: pending (from CSV) or uploaded (has PDF)', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Batch name (CSV filename or user-provided)', max_length=255)),
                ('total_expected', models.PositiveIntegerField(default=0, help_text='Total number of expected invoices from CSV')),
                ('total_uploaded', models.PositiveIntegerField(default=0, help_text='Number of invoices that have been uploaded')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='importedinvoice',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='The import batch this invoice belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoiceimportbatch'),
        ),
        migrations.AddIndex(
            model_name='importedinvoice',
            index=models.Index(fields=['tenant', 'upload_status'], name='invoices_im_tenant__df4b30_idx'),
        ),
        migrations.AddIndex(
            model_name='importedinvoice',
            index=models.Index(fields=['tenant', 'expected_filename'], name='invoices_im_tenant__f789d6_idx'),
        ),
    ]
