# Generated by Django 6.0.2 on 2026-02-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_contract_status'),
        ('invoices', '0006_add_invoice_import_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedinvoice',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Associated contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_invoices', to='contracts.contract'),
        ),
    ]
