# Generated by Django 6.0.2 on 2026-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_add_contract_to_imported_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedinvoice',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('extraction_failed', 'Extraction Failed'), ('duplicate', 'Duplicate'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
