# Generated by Django 6.0.2 on 2026-02-16 08:38

import apps.invoices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_imported_invoice'),
        ('invoices', '0009_extend_invoicerecord_status'),
        ('tenants', '0010_add_contracts_export_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoicepaymentmatch',
            name='unique_invoice_transaction_match',
        ),
        migrations.AddField(
            model_name='invoicepaymentmatch',
            name='invoice_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_matches', to='invoices.invoicerecord'),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=apps.invoices.models.invoice_record_upload_path),
        ),
        migrations.AlterField(
            model_name='invoicepaymentmatch',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_matches', to='invoices.importedinvoice'),
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('invoice', 'transaction'), name='unique_imported_tx_match'),
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_record__isnull', False)), fields=('invoice_record', 'transaction'), name='unique_record_tx_match'),
        ),
    ]
