# Generated by Django 6.0.2 on 2026-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_remove_invoicepaymentmatch_unique_invoice_transaction_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='email_sent_to',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
