# Generated by Django 6.0.2 on 2026-02-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoicerecord_email_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='The date shown on the invoice (defaults to creation date)', null=True),
        ),
    ]
