# Generated by Django 6.0.2 on 2026-02-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_replace_storno_cancelled_with_voided'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='void_reason',
            field=models.TextField(blank=True, help_text='Reason for voiding the invoice'),
        ),
    ]
