# Generated by Django 6.0.2 on 2026-02-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_backfill_invoice_audit_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedinvoice',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('extraction_failed', 'Extraction Failed'), ('duplicate', 'Duplicate'), ('confirmed', 'Confirmed'), ('sent', 'Sent'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
