# Generated by Django 6.0.2 on 2026-02-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_backfill_matched_imported_invoices_paid'),
        ('tenants', '0012_add_todos_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('storno', 'Storno (Credit Note)')], default='invoice', max_length=10),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='storno_of',
            field=models.ForeignKey(blank=True, help_text='The original invoice this storno reverses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storno_records', to='invoices.invoicerecord'),
        ),
        migrations.CreateModel(
            name='StornoNumberScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(default='S-{YYYY}-{NNNN}', help_text='Pattern with placeholders: {YYYY}, {YY}, {MM}, {NNN}, {NNNN}, {NNNNN}', max_length=100)),
                ('next_counter', models.PositiveIntegerField(default=1)),
                ('reset_period', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('never', 'Never')], default='yearly', max_length=10)),
                ('last_reset_year', models.PositiveIntegerField(blank=True, null=True)),
                ('last_reset_month', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storno_number_scheme', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Storno Number Scheme',
            },
        ),
    ]
