# Generated by Django 6.0.2 on 2026-02-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_add_storno_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylegaldata',
            name='vat_text_eu',
            field=models.TextField(blank=True, default='Steuerschuldnerschaft des Leistungsempfängers (Reverse Charge gem. § 13b UStG)', help_text='VAT sentence for EU customers (reverse charge)'),
        ),
        migrations.AddField(
            model_name='companylegaldata',
            name='vat_text_non_eu',
            field=models.TextField(blank=True, default='Umsatzsteuer nicht geschuldet gemäß § 3a Abs. 2 UStG', help_text='VAT sentence for non-EU customers (place of supply)'),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='vat_sentence',
            field=models.TextField(blank=True, help_text='Frozen VAT sentence at generation time'),
        ),
    ]
