# Generated by Django 6.0.2 on 2026-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_companylegaldata_vat_text_eu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylegaldata',
            name='vat_text_eu',
            field=models.TextField(blank=True, default='Reverse Charge – VAT liability transferred to the recipient (§ 13b UStG)', help_text='VAT sentence for EU customers (reverse charge)'),
        ),
        migrations.AlterField(
            model_name='companylegaldata',
            name='vat_text_non_eu',
            field=models.TextField(blank=True, default='VAT not applicable – place of supply rules (§ 3a(2) UStG)', help_text='VAT sentence for non-EU customers (place of supply)'),
        ),
    ]
