# Generated by Django 6.0.3 on 2026-03-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_update_vat_text_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedinvoice',
            name='billing_date',
            field=models.DateField(blank=True, help_text='Billing period date this invoice covers (set when uploaded from forecast)', null=True),
        ),
    ]
