# Generated by Django 6.0.3 on 2026-03-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_importedinvoice_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepaymentmatch',
            name='match_type',
            field=models.CharField(choices=[('invoice_number', 'Invoice Number Match'), ('amount_customer', 'Amount + Customer Match'), ('fuzzy_composite', 'Fuzzy Composite Match'), ('manual', 'Manual Match')], max_length=20),
        ),
    ]
