# Generated by Django 6.0.3 on 2026-03-26 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_fte_distribution_snapshot'),
        ('invoices', '0023_add_fuzzy_composite_match_type'),
        ('tenants', '0016_add_cost_center_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepaymentmatch',
            name='incoming_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_matches', to='banking.incominginvoice'),
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('incoming_invoice__isnull', False)), fields=('incoming_invoice', 'transaction'), name='unique_incoming_tx_match'),
        ),
    ]
