# Generated by Django 6.0.4 on 2026-05-22 06:56

import apps.invoices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_add_incoming_invoice_to_payment_match'),
        ('tenants', '0018_reportschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date (invoice_date + resolved payment term)', null=True),
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.PositiveSmallIntegerField(choices=[(0, 'Payment reminder'), (1, 'First dunning notice'), (2, 'Second dunning notice'), (3, 'Third dunning notice')])),
                ('language', models.CharField(default='de', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_rate_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate (%) applied at send time', max_digits=5)),
                ('interest_days', models.PositiveIntegerField(default=0, help_text='Overdue days the interest was calculated on')),
                ('pdf_file', models.FileField(blank=True, upload_to=apps.invoices.models.payment_reminder_upload_path)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reminders_created', to=settings.AUTH_USER_MODEL)),
                ('invoice_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='invoices.invoicerecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
