# Generated by Django 6.0.5 on 2026-06-03 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_contract_payment_term_days'),
        ('customers', '0011_customer_payment_term_days'),
        ('invoices', '0027_grant_reminder_permissions'),
        ('tenants', '0018_reportschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importedinvoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('storno', 'Storno (Credit Note)')], default='invoice', max_length=10),
        ),
        migrations.AddField(
            model_name='importedinvoice',
            name='storno_of',
            field=models.ForeignKey(blank=True, help_text='The original imported invoice this credit note reverses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storno_records', to='invoices.importedinvoice'),
        ),
        migrations.AddField(
            model_name='importedinvoice',
            name='void_reason',
            field=models.TextField(blank=True, help_text='Reason for voiding the invoice'),
        ),
        migrations.AddField(
            model_name='importedinvoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was voided', null=True),
        ),
        migrations.AddField(
            model_name='importedinvoice',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_imported_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importedinvoice',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('extraction_failed', 'Extraction Failed'), ('duplicate', 'Duplicate'), ('confirmed', 'Confirmed'), ('sent', 'Sent'), ('paid', 'Paid'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='importedinvoice',
            index=models.Index(fields=['tenant', 'document_type'], name='invoices_im_tenant__b5c61c_idx'),
        ),
    ]
