# Generated by Django 6.0.2 on 2026-02-26 16:21

import apps.offers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0030_add_estimated_delivery_date'),
        ('customers', '0008_webhook_event_log'),
        ('tenants', '0012_add_todos_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferNumberScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(default='{YYYY}-{NNNN}', help_text='Pattern with placeholders: {YYYY}, {YY}, {MM}, {NNN}, {NNNN}, {NNNNN}', max_length=100)),
                ('next_counter', models.PositiveIntegerField(default=1)),
                ('reset_period', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('never', 'Never')], default='yearly', max_length=10)),
                ('last_reset_year', models.PositiveIntegerField(blank=True, null=True)),
                ('last_reset_month', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_number_scheme', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Offer Number Scheme',
            },
        ),
        migrations.CreateModel(
            name='OfferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_number', models.CharField(help_text='Assigned sequential offer number', max_length=100)),
                ('offer_date', models.DateField(help_text='The date shown on the offer')),
                ('valid_until', models.DateField(blank=True, help_text='Offer validity expiration date', null=True)),
                ('billing_date', models.DateField(help_text='The billing date from the forecast event')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_items_snapshot', models.JSONField(help_text='Frozen copy of line items at generation time')),
                ('company_data_snapshot', models.JSONField(help_text='Frozen copy of company legal data at generation time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('customer_name', models.CharField(max_length=255)),
                ('contract_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Offer conditions/notes (rendered in PDF)')),
                ('pdf_file', models.FileField(blank=True, upload_to=apps.offers.models.offer_record_upload_path)),
                ('vat_sentence', models.TextField(blank=True, help_text='Frozen VAT sentence at generation time')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_to', models.JSONField(blank=True, default=list)),
                ('email_message_id', models.CharField(blank=True, max_length=255)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_records', to='contracts.contract')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_records', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-offer_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'offer_number'), name='unique_offer_number_per_tenant')],
            },
        ),
    ]
