# Generated by Django 6.0.3 on 2026-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrecord',
            name='scoped_item_ids',
            field=models.JSONField(blank=True, help_text='List of contract item IDs this offer covers. Null = all items.', null=True),
        ),
    ]
