# Generated by Django 6.0.5 on 2026-06-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offerrecord_scoped_item_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrecord',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='offers.offerrecord'),
        ),
        migrations.AddField(
            model_name='offerrecord',
            name='free_text_after_items',
            field=models.TextField(blank=True, default='', help_text='Markdown rendered directly below the line-item table.'),
        ),
        migrations.AddField(
            model_name='offerrecord',
            name='free_text_before_terms',
            field=models.TextField(blank=True, default='', help_text='Markdown rendered directly above the VAT block and any T&C section.'),
        ),
        migrations.AddField(
            model_name='offerrecord',
            name='minimum_term_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerrecord',
            name='notice_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('finalized', 'Finalized'), ('accepted', 'Accepted (legacy)'), ('rejected', 'Rejected (legacy)'), ('cancelled', 'Cancelled (legacy)')], default='draft', max_length=10),
        ),
    ]
