# Generated by Django 6.0.1 on 2026-01-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_start_date', models.DateField()),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('billing_anchor_day', models.PositiveSmallIntegerField(default=1)),
                ('min_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_period_months', models.PositiveIntegerField(default=3)),
                ('notice_period_anchor', models.CharField(choices=[('end_of_duration', 'End of minimum duration'), ('end_of_month', 'End of month'), ('end_of_quarter', 'End of quarter')], default='end_of_duration', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_effective_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField()),
                ('type', models.CharField(choices=[('product_added', 'Product added'), ('product_removed', 'Product removed'), ('quantity_changed', 'Quantity changed'), ('price_changed', 'Price changed'), ('terms_changed', 'Terms changed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_source', models.CharField(choices=[('list', 'From price list'), ('custom', 'Custom price'), ('customer_agreement', 'Customer agreement')], default='list', max_length=20)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
