# Generated by Django 6.0.1 on 2026-01-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
