# Generated by Django 6.0.1 on 2026-01-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='align_to_contract_at',
            field=models.DateField(blank=True, help_text='Date when this item aligns to contract billing cycle. First period is pro-rated.', null=True),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='billing_end_date',
            field=models.DateField(blank=True, help_text='When billing ends for this item. Null = ongoing.', null=True),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='When billing starts for this item. Defaults to contract billing start.', null=True),
        ),
    ]
