# Generated by Django 6.0.1 on 2026-01-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_add_billing_fields_to_contract_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='start_date',
            field=models.DateField(blank=True, help_text='When this item becomes effective. Defaults to today if not set.', null=True),
        ),
    ]
