# Generated by Django 6.0.1 on 2026-01-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractitem_start_date'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hubspot_deal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('tenant', 'hubspot_deal_id')},
        ),
    ]
