# Generated by Django 6.0.1 on 2026-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_hubspot_deal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='is_one_off',
            field=models.BooleanField(default=False, help_text='If True, this item is billed only once (not recurring).'),
        ),
    ]
