# Generated by Django 6.0.1 on 2026-01-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contractitem_is_one_off'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notice_period_after_min_months',
            field=models.PositiveIntegerField(blank=True, help_text='Notice period after minimum duration ends (if different from notice_period_months)', null=True),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='price_locked',
            field=models.BooleanField(default=False, help_text='If True, price cannot be changed until price_locked_until.'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='price_locked_until',
            field=models.DateField(blank=True, help_text='Date until price is locked. After this date, price_locked becomes False.', null=True),
        ),
        migrations.CreateModel(
            name='ContractItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(help_text='Start date for this price period')),
                ('valid_to', models.DateField(blank=True, help_text='End date for this price period. Null = ongoing.', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Monthly unit price during this period', max_digits=10)),
                ('source', models.CharField(choices=[('fixed', 'Fixed Agreement'), ('list', 'List Price'), ('negotiated', 'To Be Negotiated')], default='fixed', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_periods', to='contracts.contractitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['valid_from'],
            },
        ),
    ]
