# Generated by Django 6.0.1 on 2026-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_notice_period_after_min_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total discount amount for this contract (from Sales Discount rows)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='netsuite_contract_number',
            field=models.CharField(blank=True, help_text="Contract number from NetSuite (e.g., '13634_2025-01-01_2025-12-31')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='netsuite_sales_order_number',
            field=models.CharField(blank=True, help_text="Sales Order number from NetSuite (e.g., 'SO-VSX-25-039')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes (e.g., invoicing instructions)'),
        ),
    ]
