# Generated by Django 6.0.1 on 2026-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order number', max_length=100, null=True),
        ),
    ]
