# Generated by Django 6.0.1 on 2026-01-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_add_po_number_to_contract'),
        ('products', '0004_product_netsuite_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description or notes for this line item'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Optional for descriptive-only line items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='products.product'),
        ),
    ]
