# Generated by Django 6.0.1 on 2026-01-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_add_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='price_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bi_monthly', '2 Months'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', help_text='The period this price refers to (e.g., monthly, quarterly, annual)', max_length=20),
        ),
        migrations.AddField(
            model_name='contractitemprice',
            name='price_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bi_monthly', '2 Months'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', help_text='The period this price refers to (e.g., monthly, quarterly, annual)', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractitemprice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price during this period', max_digits=10),
        ),
    ]
