# Generated by Django 6.0.1 on 2026-02-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_add_price_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual'), ('biennial', '2 Years'), ('triennial', '3 Years'), ('quadrennial', '4 Years'), ('quinquennial', '5 Years')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='price_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bi_monthly', '2 Months'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual'), ('biennial', '2 Years'), ('triennial', '3 Years'), ('quadrennial', '4 Years'), ('quinquennial', '5 Years')], default='monthly', help_text='The period this price refers to (e.g., monthly, quarterly, annual)', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractitemprice',
            name='price_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bi_monthly', '2 Months'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual'), ('biennial', '2 Years'), ('triennial', '3 Years'), ('quadrennial', '4 Years'), ('quinquennial', '5 Years')], default='monthly', help_text='The period this price refers to (e.g., monthly, quarterly, annual)', max_length=20),
        ),
    ]
