# Generated by Django 6.0.1 on 2026-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_add_multi_year_billing_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='order_confirmation_number',
            field=models.CharField(blank=True, help_text='Order Confirmation number (AB Nummer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='order_confirmation_number',
            field=models.CharField(blank=True, help_text='Order Confirmation number (AB Nummer) for this item', max_length=100, null=True),
        ),
    ]
