# Generated by Django 6.0.1 on 2026-02-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_add_order_confirmation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='invoice_text',
            field=models.TextField(blank=True, help_text='Optional text to show on invoices below line items'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (not shown on invoices)'),
        ),
    ]
