# Generated by Django 6.0.1 on 2026-02-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_add_invoice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='netsuite_url',
            field=models.URLField(blank=True, help_text='Link to this contract in NetSuite', max_length=500, null=True),
        ),
    ]
