# Generated by Django 6.0.1 on 2026-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_add_netsuite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='billing_alignment_date',
            field=models.DateField(blank=True, help_text='Date when billing aligns to regular cycle. First invoice covers period from billing_start_date to this date (pro-rated).', null=True),
        ),
    ]
