# Generated by Django 6.0.1 on 2026-02-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_add_links_and_customer_attachments'),
        ('tenants', '0003_add_time_tracking_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackingProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_project_id', models.CharField(max_length=100)),
                ('external_project_name', models.CharField(max_length=255)),
                ('external_customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking_mappings', to='contracts.contract')),
                ('contract_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_tracking_mappings', to='contracts.contractitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['external_customer_name', 'external_project_name'],
                'unique_together': {('tenant', 'external_project_id')},
            },
        ),
    ]
