# Generated by Django 6.0.2 on 2026-02-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_add_sort_order_to_contract_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
    ]
