# Generated by Django 6.0.2 on 2026-02-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_contract_status'),
        ('customers', '0005_add_invoice_import_batch'),
        ('tenants', '0009_add_invoices_delete_write_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_groups', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contractgroup'),
        ),
    ]
