# Generated by Django 6.0.2 on 2026-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_contractgroup_contract_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrackingprojectmapping',
            name='cached_by_month',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='timetrackingprojectmapping',
            name='cached_by_service',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='timetrackingprojectmapping',
            name='cached_total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='timetrackingprojectmapping',
            name='cached_total_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='timetrackingprojectmapping',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
