# Generated by Django 6.0.2 on 2026-02-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_timetrackingprojectmapping_cached_by_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractattachment',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Cached AI extraction result (line items + metadata). Persisted to avoid repeated API calls.', null=True),
        ),
    ]
