# Generated by Django 6.0.2 on 2026-02-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_add_extracted_data_to_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='delivered_at',
            field=models.DateField(blank=True, help_text='Date when this item was delivered.', null=True),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('delivered', 'Delivered')], help_text='Delivery tracking: NULL = no tracking, pending = awaiting delivery, delivered = completed.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Item that must be delivered before this one can be billed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_items', to='contracts.contractitem'),
        ),
    ]
