# Generated by Django 6.0.2 on 2026-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_contractcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Estimated delivery date for pending deliverable items. Used for revenue forecasting.', null=True),
        ),
    ]
