# Generated by Django 6.0.2 on 2026-02-27 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_contractitem_revenue_type'),
        ('tenants', '0012_add_todos_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('revenue_type', models.CharField(choices=[('advanced_development', 'Advanced Development'), ('training_implementation', 'Training + Implementation'), ('recurring', 'Recurring Revenue')], max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['year', 'revenue_type'],
                'unique_together': {('tenant', 'year', 'revenue_type')},
            },
        ),
    ]
