# Generated by Django 6.0.2 on 2026-02-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_add_revenue_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='deal_won_date',
            field=models.DateField(blank=True, help_text='Date the deal was won (from HubSpot closedate for imported deals)', null=True),
        ),
    ]
