# Generated by Django 6.0.2 on 2026-02-28 22:06

from django.db import migrations
from django.db.models import F


def backfill_deal_won_date(apps, schema_editor):
    Contract = apps.get_model("contracts", "Contract")
    Contract.objects.filter(
        hubspot_deal_id__isnull=False,
        deal_won_date__isnull=True,
    ).exclude(hubspot_deal_id="").update(
        deal_won_date=F("start_date"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0033_add_deal_won_date"),
    ]

    operations = [
        migrations.RunPython(backfill_deal_won_date, migrations.RunPython.noop),
    ]
