# Generated by Django 6.0.2 on 2026-02-28 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_backfill_deal_won_date'),
        ('tenants', '0012_add_todos_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBusinessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('goal_type', models.CharField(choices=[('new_arr', 'Won New ARR'), ('new_development', 'Won Development Revenue'), ('new_deal_count', 'Won Deal Count')], max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['year', 'goal_type'],
                'unique_together': {('tenant', 'year', 'goal_type')},
            },
        ),
    ]
