# Generated by Django 6.0.2 on 2026-03-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_add_new_business_goal'),
        ('tenants', '0012_add_todos_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrackingprojectmapping',
            name='link_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='AutoLinkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('starts_with', 'Starts with')], default='contains', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_link_rules', to='contracts.contract')),
                ('contract_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_link_rules', to='contracts.contractitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='timetrackingprojectmapping',
            name='auto_link_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mappings', to='contracts.autolinkrule'),
        ),
    ]
