# Generated by Django 6.0.2 on 2026-03-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_department_departmentservicemapping'),
        ('tenants', '0012_add_todos_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_user_id', models.CharField(max_length=50)),
                ('external_user_name', models.CharField(max_length=255)),
                ('fte_percentage', models.IntegerField(default=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_profiles', to='contracts.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'external_user_id')},
            },
        ),
    ]
