# Generated by Django 6.0.2 on 2026-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_user_cost_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitemprice',
            name='increase_type',
            field=models.CharField(blank=True, choices=[('inflation', 'Inflation'), ('negotiated', 'Negotiated')], help_text='Reason for price change (inflation or negotiated)', max_length=20, null=True),
        ),
    ]
