# Generated by Django 6.0.2 on 2026-03-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_add_order_confirmation'),
        ('contracts', '0039_contractitemprice_increase_type'),
    ]

    operations = [
    ]
