# Generated by Django 6.0.2 on 2026-03-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0040_merge_20260304_1624'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderconfirmation',
            new_name='contracts_o_tenant__ab6eed_idx',
            old_name='contracts_o_tenant__idx',
        ),
    ]
