# Generated by Django 6.0.3 on 2026-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0041_rename_contracts_o_tenant__idx_contracts_o_tenant__ab6eed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractamendment',
            name='arr_delta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annualized revenue delta caused by this amendment', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='newbusinessgoal',
            name='goal_type',
            field=models.CharField(choices=[('new_arr', 'Won New ARR'), ('back_to_base_arr', 'Back-to-Base ARR'), ('new_development', 'Won Development Revenue'), ('new_deal_count', 'Won Deal Count')], max_length=30),
        ),
    ]
