# Generated by Django 6.0.3 on 2026-03-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0042_add_amendment_arr_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='source_hubspot_deal_id',
            field=models.CharField(blank=True, help_text='HubSpot deal ID from source contract when item was transferred via merge.', max_length=255, null=True),
        ),
    ]
