# Generated by Django 6.0.3 on 2026-03-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_remove_costcentersplitrule_split_rule_must_have_matcher_and_more'),
        ('contracts', '0043_contractitem_source_hubspot_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='banking.costcenter'),
        ),
    ]
