# Generated by Django 6.0.3 on 2026-03-20 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_department_cost_center'),
        ('tenants', '0016_add_cost_center_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='absence_reports/')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_absence_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AbsenceReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=255)),
                ('external_user_id', models.CharField(max_length=100)),
                ('absence_type', models.CharField(choices=[('sick', 'Sick'), ('sick_child', 'Sick (child)'), ('sick_certificate', 'Sick (with certificate)'), ('vacation', 'Vacation'), ('special_leave', 'Special leave'), ('education', 'Education/Training'), ('overtime_reduction', 'Overtime reduction'), ('other', 'Other')], max_length=30)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('days_count', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contracts.absencereport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['user_name', 'date_from'],
            },
        ),
    ]
