# Generated by Django 6.0.3 on 2026-03-31 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0045_absence_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='moved_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='contracts.contractitem'),
        ),
    ]
