# Generated by Django 6.0.3 on 2026-04-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0046_contractitem_moved_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='deal_won_date',
            field=models.DateField(blank=True, help_text='Date this specific item was won/booked. Used for new bookings reporting when different from contract deal_won_date.', null=True),
        ),
    ]
