# Generated by Django 6.0.3 on 2026-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0047_contractitem_deal_won_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractattachment',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Document category: order, contract, offer, other', max_length=50),
        ),
    ]
