# Generated by Django 6.0.4 on 2026-04-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0048_add_attachment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='invoice_independent',
            field=models.BooleanField(default=False, help_text='If True, this item is billed regardless of delivery status (e.g. upfront payment). Delivery tracking is kept for documentation only.'),
        ),
    ]
