# Generated by Django 6.0.4 on 2026-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0049_contractitem_invoice_independent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='offer_number',
            field=models.CharField(blank=True, help_text='Offer number (VSX) — usually copied from the related deal/offer when the contract is created', max_length=100, null=True),
        ),
    ]
