# Generated by Django 6.0.4 on 2026-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0050_contract_offer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_term_days',
            field=models.PositiveIntegerField(blank=True, help_text='Payment term in days. Empty means fall back to customer, then tenant default.', null=True),
        ),
    ]
