# Generated by Django 6.0.5 on 2026-06-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_contract_payment_term_days'),
        ('offers', '0003_offerrecord_cloned_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractattachment',
            name='source_offer',
            field=models.ForeignKey(blank=True, help_text='When this attachment was produced by an offer transitioning to sent or finalized, points back to the source OfferRecord. SET_NULL on offer delete so the attachment survives as the historical record of what the customer received.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_attachments', to='offers.offerrecord'),
        ),
    ]
