# Generated by Django 6.0.1 on 2026-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_billing_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='netsuite_item_name',
            field=models.CharField(blank=True, help_text="Item name from NetSuite (e.g., 'Hosting + Maintenance : Software Maintenance')", max_length=255, null=True),
        ),
    ]
