# Generated by Django 6.0.2 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_netsuite_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override tax rate in % (e.g. 7.00). Empty = use company default.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
