# Generated by Django 6.0.2 on 2026-02-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_netsuite_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='revenue_type',
            field=models.CharField(blank=True, choices=[('advanced_development', 'Advanced Development'), ('training_implementation', 'Training + Implementation'), ('recurring', 'Recurring Revenue')], help_text='Revenue stream classification: Advanced Development, Training + Implementation, or Recurring', max_length=30, null=True),
        ),
    ]
