# Generated by Django 6.0.2 on 2026-02-27 19:35

from django.db import migrations


def set_subscription_revenue_type(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(type="subscription", revenue_type__isnull=True).update(
        revenue_type="recurring"
    )


def reverse_subscription_revenue_type(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(type="subscription", revenue_type="recurring").update(
        revenue_type=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_revenue_type'),
    ]

    operations = [
        migrations.RunPython(
            set_subscription_revenue_type,
            reverse_subscription_revenue_type,
        ),
    ]
