# Generated by Django 6.0.2 on 2026-02-09 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0007_migrate_invoice_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='User-given label', max_length=255)),
                ('bank_code', models.CharField(help_text='BLZ / routing number from MT940 :25: field', max_length=20)),
                ('account_number', models.CharField(help_text='Account number from MT940 :25: field', max_length=30)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('bic', models.CharField(blank=True, max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField(help_text='Booking date from :61: field')),
                ('value_date', models.DateField(blank=True, help_text='Value/settlement date from :61: field', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credit, negative for debit', max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('transaction_type', models.CharField(blank=True, help_text='SWIFT type code (e.g. NTRF, NDDT)', max_length=10)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('counterparty_iban', models.CharField(blank=True, max_length=50)),
                ('counterparty_bic', models.CharField(blank=True, max_length=20)),
                ('booking_text', models.TextField(blank=True, help_text='Verwendungszweck from :86: ?20-?29 subfields')),
                ('reference', models.CharField(blank=True, help_text='EREF/KREF/MREF combined', max_length=500)),
                ('raw_data', models.TextField(blank=True, help_text='Full :86: field content for debugging')),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('import_hash', models.CharField(help_text='SHA256 hash for deduplication', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'bank_code', 'account_number'), name='unique_bank_account_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['tenant', 'account', 'entry_date'], name='idx_txn_tenant_account_date'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount'], name='idx_txn_amount'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['counterparty_name'], name='idx_txn_counterparty'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'import_hash'), name='unique_transaction_hash_per_tenant'),
        ),
    ]
