# Generated by Django 6.0.2 on 2026-02-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('tenants', '0008_add_banking_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_name', models.CharField(max_length=255)),
                ('counterparty_iban', models.CharField(blank=True, max_length=50)),
                ('average_amount', models.DecimalField(decimal_places=2, help_text='Average transaction amount (negative for costs)', max_digits=14)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('irregular', 'Irregular')], default='monthly', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Typical day of month for payment (1-31)', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Detection confidence (0.0-1.0)')),
                ('is_confirmed', models.BooleanField(default=False, help_text='User has confirmed this pattern')),
                ('is_ignored', models.BooleanField(default=False, help_text='User has dismissed this pattern')),
                ('is_paused', models.BooleanField(default=False, help_text='Temporarily excluded from projections')),
                ('last_occurrence', models.DateField(blank=True, help_text='Date of most recent matching transaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_transactions', models.ManyToManyField(blank=True, related_name='recurring_patterns', to='banking.banktransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-confidence_score', '-last_occurrence'],
                'indexes': [models.Index(fields=['tenant', 'is_confirmed', 'is_ignored'], name='idx_pattern_tenant_status')],
            },
        ),
    ]
