# Generated by Django 6.0.2 on 2026-02-10 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_recurring_pattern'),
        ('tenants', '0008_add_banking_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpattern',
            name='counterparty_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('bic', models.CharField(blank=True, max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'counterparties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Reference to counterparty entity', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.counterparty'),
        ),
        migrations.AddField(
            model_name='recurringpattern',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Reference to counterparty entity', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_patterns', to='banking.counterparty'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['tenant', 'name'], name='idx_counterparty_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_counterparty_name_per_tenant'),
        ),
    ]
