# Generated by Django 6.0.2 on 2026-02-10 13:29

from django.db import migrations


def populate_counterparties(apps, schema_editor):
    """
    Extract unique counterparty names from transactions, create Counterparty records,
    and link all transactions/patterns to them.
    """
    BankTransaction = apps.get_model("banking", "BankTransaction")
    RecurringPattern = apps.get_model("banking", "RecurringPattern")
    Counterparty = apps.get_model("banking", "Counterparty")

    # Get all unique (tenant_id, counterparty_name) combinations from transactions
    # along with first non-empty IBAN/BIC
    counterparty_data = {}

    for txn in BankTransaction.objects.exclude(counterparty_name="").iterator():
        key = (txn.tenant_id, txn.counterparty_name)
        if key not in counterparty_data:
            counterparty_data[key] = {
                "tenant_id": txn.tenant_id,
                "name": txn.counterparty_name,
                "iban": txn.counterparty_iban or "",
                "bic": txn.counterparty_bic or "",
            }
        else:
            # Update IBAN/BIC if current record has empty and this one has data
            if not counterparty_data[key]["iban"] and txn.counterparty_iban:
                counterparty_data[key]["iban"] = txn.counterparty_iban
            if not counterparty_data[key]["bic"] and txn.counterparty_bic:
                counterparty_data[key]["bic"] = txn.counterparty_bic

    # Also check RecurringPattern for any counterparties not in transactions
    for pattern in RecurringPattern.objects.exclude(counterparty_name="").iterator():
        key = (pattern.tenant_id, pattern.counterparty_name)
        if key not in counterparty_data:
            counterparty_data[key] = {
                "tenant_id": pattern.tenant_id,
                "name": pattern.counterparty_name,
                "iban": pattern.counterparty_iban or "",
                "bic": "",
            }
        elif not counterparty_data[key]["iban"] and pattern.counterparty_iban:
            counterparty_data[key]["iban"] = pattern.counterparty_iban

    # Create Counterparty records (skip if already exists for idempotency)
    counterparty_map = {}  # (tenant_id, name) -> Counterparty instance

    for key, data in counterparty_data.items():
        counterparty, _ = Counterparty.objects.get_or_create(
            tenant_id=data["tenant_id"],
            name=data["name"],
            defaults={"iban": data["iban"], "bic": data["bic"]},
        )
        counterparty_map[key] = counterparty

    # Update all BankTransactions to reference their Counterparty
    for txn in BankTransaction.objects.filter(counterparty__isnull=True).exclude(
        counterparty_name=""
    ):
        key = (txn.tenant_id, txn.counterparty_name)
        if key in counterparty_map:
            txn.counterparty = counterparty_map[key]
            txn.save(update_fields=["counterparty"])

    # Handle transactions with empty counterparty_name - create "Unknown" counterparty per tenant
    unknown_counterparties = {}  # tenant_id -> Counterparty
    for txn in BankTransaction.objects.filter(counterparty__isnull=True, counterparty_name=""):
        if txn.tenant_id not in unknown_counterparties:
            unknown_cp, _ = Counterparty.objects.get_or_create(
                tenant_id=txn.tenant_id,
                name="(Unknown)",
                defaults={"iban": "", "bic": ""},
            )
            unknown_counterparties[txn.tenant_id] = unknown_cp
        txn.counterparty = unknown_counterparties[txn.tenant_id]
        txn.save(update_fields=["counterparty"])

    # Update all RecurringPatterns to reference their Counterparty
    for pattern in RecurringPattern.objects.filter(counterparty__isnull=True).exclude(
        counterparty_name=""
    ):
        key = (pattern.tenant_id, pattern.counterparty_name)
        if key in counterparty_map:
            pattern.counterparty = counterparty_map[key]
            pattern.save(update_fields=["counterparty"])

    # Handle patterns with empty counterparty_name
    for pattern in RecurringPattern.objects.filter(counterparty__isnull=True, counterparty_name=""):
        if pattern.tenant_id not in unknown_counterparties:
            unknown_cp, _ = Counterparty.objects.get_or_create(
                tenant_id=pattern.tenant_id,
                name="(Unknown)",
                defaults={"iban": "", "bic": ""},
            )
            unknown_counterparties[pattern.tenant_id] = unknown_cp
        pattern.counterparty = unknown_counterparties[pattern.tenant_id]
        pattern.save(update_fields=["counterparty"])


def reverse_populate(apps, schema_editor):
    """Reverse: clear all counterparty FKs (data stays in legacy fields)."""
    BankTransaction = apps.get_model("banking", "BankTransaction")
    RecurringPattern = apps.get_model("banking", "RecurringPattern")
    Counterparty = apps.get_model("banking", "Counterparty")

    BankTransaction.objects.update(counterparty=None)
    RecurringPattern.objects.update(counterparty=None)
    Counterparty.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_counterparty_model"),
    ]

    operations = [
        migrations.RunPython(populate_counterparties, reverse_populate),
    ]
