# Generated by Django 6.0.2 on 2026-02-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_populate_counterparties'),
        ('tenants', '0008_add_banking_permissions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banktransaction',
            name='idx_txn_counterparty',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='counterparty_iban',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='counterparty_name',
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='counterparty',
            field=models.ForeignKey(help_text='Reference to counterparty entity', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.counterparty'),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='counterparty',
            field=models.ForeignKey(help_text='Reference to counterparty entity', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_patterns', to='banking.counterparty'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['counterparty'], name='idx_txn_counterparty'),
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='counterparty_bic',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='counterparty_iban',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='counterparty_name',
        ),
    ]
