# Generated by Django 6.0.2 on 2026-02-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_finalize_counterparty_fk'),
        ('customers', '0004_add_links_and_customer_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Linked customer for payment matching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='customers.customer'),
        ),
    ]
