# Generated by Django 6.0.3 on 2026-03-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_imported_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='exclude_from_forecast',
            field=models.BooleanField(default=False),
        ),
    ]
