# Generated by Django 6.0.3 on 2026-03-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_merge_cost_center_invoice_inbox'),
        ('tenants', '0015_signupverification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='costcentersplitrule',
            name='split_rule_must_have_matcher',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='exclude_from_forecast',
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='invoiceinbox',
            name='m365_mailbox',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceinbox',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceinbox',
            name='password',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='costcentersplitrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking_text_pattern__isnull', True), ('counterparty__isnull', True), _negated=True), models.Q(('booking_text_pattern', ''), ('counterparty__isnull', True), _negated=True)), name='split_rule_must_have_matcher'),
        ),
    ]
