# Generated by Django 6.0.3 on 2026-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_remove_costcentersplitrule_split_rule_must_have_matcher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentersplitrule',
            name='mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('fte_distribution', 'FTE Distribution')], default='percentage', max_length=20),
        ),
    ]
