# Generated by Django 6.0.3 on 2026-03-12 17:14

from django.db import migrations


def populate_mode(apps, schema_editor):
    """Set mode based on existing allocation fields."""
    CostCenterSplitRule = apps.get_model("banking", "CostCenterSplitRule")
    for rule in CostCenterSplitRule.objects.all():
        first_alloc = rule.allocations.first()
        if first_alloc and first_alloc.fixed_amount is not None:
            rule.mode = "fixed_amount"
            rule.save(update_fields=["mode"])
        # else keep default "percentage"


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0011_split_rule_mode"),
    ]

    operations = [
        migrations.RunPython(populate_mode, migrations.RunPython.noop),
    ]
