# Generated by Django 6.0.3 on 2026-03-12 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_populate_split_rule_mode'),
        ('contracts', '0044_department_cost_center'),
        ('tenants', '0016_add_cost_center_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FteDistributionSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_month', models.CharField(help_text='YYYY-MM format, e.g. 2026-03', max_length=7)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_fte_snapshots', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-year_month'],
                'unique_together': {('tenant', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='FteDistributionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('cost_center_code', models.CharField(max_length=20)),
                ('fte_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('monthly_income_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('hours_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.department')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='banking.ftedistributionsnapshot')),
            ],
            options={
                'ordering': ['-fte_percentage'],
            },
        ),
    ]
