# Generated by Django 6.0.3 on 2026-03-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_fte_distribution_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginvoice',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of PDF content for deduplication', max_length=64),
        ),
    ]
