# Generated by Django 6.0.4 on 2026-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_add_content_hash_to_incoming_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginvoice',
            name='extraction_confidence',
            field=models.JSONField(blank=True, default=dict, help_text='Per-field AI confidence scores 0.0–1.0'),
        ),
    ]
